import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import FilesSection from '@/components/FilesSection'
import useSWR from 'swr'
import { FileData, getFiles } from '@/lib/getFiles'
import { buildFilesTree } from '@/lib/buildFilesTree'
import { SWRConfig } from 'swr/_internal'

const inter = Inter({ subsets: ['latin'] })

const filesApi = '/api/files'
const fetcher = (url: string) =>
  fetch(url).then((res) => res.json() as Promise<FileData[]>)

export async function getServerSideProps() {
  const files = await getFiles()
  const filesTree = buildFilesTree(files)
  return {
    props: {
      fallback: { [filesApi]: filesTree },
    },
  }
}

function Home() {
  const { data, error, isLoading } = useSWR<FileData[], Error>(
    filesApi,
    fetcher,
    { refreshInterval: 30000 }
  )

  if (error) {
    return <>Error loading files</>
  }

  if (!data) {
    return <>Loading files...</>
  }

  return (
    <>
      <Head>
        <title>Next File Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <FilesSection filesTree={data} />
      </main>
    </>
  )
}

export default function App({ fallback }: { fallback: FileData[] }) {
  return (
    <SWRConfig value={{ fallback }}>
      <Home />
    </SWRConfig>
  )
}
